### ISSUE TITLE
Output of SeqMem invalid for one cycle

### ISSUE THREAD

**Issue by grebe** [ucb-art/builtin-debugger#5]
Munir discovered a problem where the output of the PG is garbage on the first valid cycle. I think what is happening is that the PG is triggered immediately as it is armed and the valid goes high (and counter starts counting) one cycle too early. The SeqMem has a delay that is not being accounted for here.

I think one solution is to add a check that the previous state was sArmed to [this line](https://github.com/ucb-art/builtin-debugger/blob/master/src/main/scala/PatternGenerator.scala#L173) that defines `combinationalTriggerFire` - what do you think @ducky64? I'll make a PR that does this unless you want it done another way.

**Comment by ducky64** [comment]
Good catch... this should be added to the test cases. I think a solution would be to register the first buffer element so it is available before the SeqMem has a chance to do the read.

Another solution might be to introduce a transient state sArming (one cycle between sIdle and sArmed), that is entered only in combinational trigger mode. It introduces a gotcha (can't trigger immediately after arming), but makes it explicit.

As for adding a check in `combinationalTriggerFire`, I think the device behavior should be that in the sArmed state and combinational mode, a valid trigger should mean valid output. Otherwise, it becomes a hidden gotcha...

**Comment by grebe** [comment]
I think I'd worry about the register of the first buffer element being incorrect. A pathological case is if you never write anything to the PG and just start playing out.

Adding an `sArming` state sounds good, but I think we want to make the name clearly describe what it does, so maybe `sArmingForCombinationalTrigger` or something like that would be better.

**Comment by ducky64** [comment]
If you never write anything to the PG then I think the expected output is undefined. If you want to define it, we can always add a RegInit, but it also needs to be consistent with SRAM init.

I think the only downside of adding a registered first element is the additional area cost. I don't know if that's significant, but it eliminates a gotcha completely, which is really nice,

**Comment by grebe** [comment]
I agree that the output is undefined, but you might reasonably expect the output to be undefined but stay the same when you play it out over and over. I guess if you never look at address 0 and always play it out from the register that would be fine. 

The area cost is insignificant though. The additional mux adds some delay, but it is easily pipelined if we need to (so far it doesn't look too bad).

**Comment by grebe** [comment]
(I should say, the area cost is insignificant for our current design. Other people might care.)

**Comment by ducky64** [comment]
That's fair, I guess the system would have to be set up such that it always reads from the reg when addr 0 is requested (instead of only during the sArmed state).

For now, my philosophy is ease-of-use over QoR micro-optimization (with avoiding gotchas being especially important). If someone complains about QoR with a solid pathological case, we can examine other solutions.

**Comment by grebe** [comment]
Which do you prefer? An "address 0 register" or an arming state? We aren't doing any fancy triggering, so I think an arming state might make the most sense. @stevobailey what do you think?

**Comment by grebe** [comment]
Stevo says he doesn't like the extra register

**Comment by ducky64** [comment]
I like the register because it keeps the interface nice and clean (and also allows for triggering immediately after arming, instead of a one-cycle delay), though the arming state is architecturally cleaner.

But either is fine. If you don't want the register, then arming state it is.
